name: Build and deploy site on push.

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: installing dependencies 
        run: sudo apt-get update && sudo apt-get install -y imagemagick pandoc

      # getting psg and putting it in our $PATH
      - name: setting up psg
        run:  |
          wget https://raw.githubusercontent.com/hendersonreed/psg/main/psg.py
          chmod +x psg.py
          mkdir -p $HOME/.local/bin/
          echo "$HOME/.local/bin/" >> $GITHUB_PATH
          mv psg.py $HOME/.local/bin/psg
      
      # actually building the site.
      - name: build the site
        run:  ./tools/heavy-lifting.sh

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy docs --project-name=henderson-lol
